GeekLab/ViewModels/Category/Partial/CategoryFormViewModel.cs
using GeekLab.ViewModels.Base;

namespace GeekLab.ViewModels.Category.Partial
{
    public class CategoryFormViewModel : GeekLabViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

GeekLab/Controllers/CategoryController.cs
using GeekLab.Commerce.Dto.Category;
using GeekLab.Commerce.IData.Interfaces;
using GeekLab.ViewModels.Category;
using GeekLab.ViewModels.Category.Partial;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net;


namespace GeekLab.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private ICategoryRepository CategoryRepository { get; }

        public CategoryController(ICategoryRepository categoryRepository)
        {

            CategoryRepository = categoryRepository;
        }
        public IActionResult Index()
        {
            var vm = new IndexViewModel()
            {
                Categories = CategoryRepository.GetCategories()
            };
            return View(vm);
        }

        public IActionResult GetCategory(int id)
        {
            return Json(CategoryRepository.GetCategory(id));
        }

        [HttpPost]
        public IActionResult CategoryForm(CategoryFormViewModel categoryFormViewModel)
        {
            var setResult = CategoryRepository.SetCategory(new CategoryDto()
            {
                Id = categoryFormViewModel.Id,
                Name = categoryFormViewModel.Name
            });
            if (!setResult.IsSuccess)
            {
                Response.StatusCode = (int)HttpStatusCode.InternalServerError;
            }
            return Json(setResult);
        }

        [HttpDelete]
        public IActionResult RemoveCategory(int id)
        {
            var removeResult = CategoryRepository.RemoveCategory(id);
            if (!removeResult.IsSuccess)
            {
                Response.StatusCode = (int)HttpStatusCode.InternalServerError;
            }
            return Json(removeResult);
        }
    }
}

GeekLab/Controllers/ProductController.cs
using GeekLab.Commerce.Dto.Product;
using GeekLab.Commerce.IData.Interfaces;
using GeekLab.Utils;
using GeekLab.ViewModels.Product;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace GeekLab.Controllers
{
    public class ProductController : Controller
    {


        private const int DefaultPageNumber = 1;
        private const int DefaultPageSize = 1;
        private IProductRepository ProductRepository { get; }
        private ICategoryRepository CategoryRepository { get; }
        public ProductController(IProductRepository productRepository
            , ICategoryRepository categoryRepository)
        {
            ProductRepository = productRepository;
            CategoryRepository = categoryRepository;
        }
        public async Task<IActionResult> Index(int? pageNumber, int? pageSize, string query)
        {
            //if (pageNumber == null)
            //{
            //    pageNumber = 1;
            //}
            pageNumber = pageNumber ?? DefaultPageNumber;
            pageSize = pageSize ?? DefaultPageSize;

            var pageResult = ProductRepository.GetProductsPage
                (pageNumber.Value - 1, pageSize.Value, query);


            var productPagedList = new StaticPagedList<ProductDto>
                (
                    pageResult.Results,
                    pageNumber.Value,
                    pageSize.Value,
                    pageResult.TotalResultsCount
                );
            var vm = new IndexViewModel()
            {
                PageResult = pageResult,
                ProductPagedList = productPagedList
            };
            if (Request.IsAjaxRequest())
            {
                var partialAsString = await this.RenderViewAsync(PathsViews._ProductsResults, vm, true);
                //ajax return
                return Json(partialAsString);
            }
            return View(vm);
        }

        public IActionResult ProductForm()
        {
            var vm = new ProductFormViewModel()
            {
                Categories = CategoryRepository.GetCategories()
                .Select(catDto => new SelectListItem()
                {
                    Value = catDto.Id.ToString(),
                    Text = catDto.Name
                }).ToList()
            };
            return View(vm);
        }

        public IActionResult ViewProduct(int id)
        {
            return null;
        }

        public IActionResult ViewProductPosts(int id)
        {
            return null;
        }

        [HttpPost]
        public IActionResult ProductForm(ProductFormViewModel productFormViewModel)
        {
            //var productName = HttpContext.Request.Form["productName"];
            //var description = HttpContext.Request.Form["description"];
            //   return Content($"Product saved successfully {productFormViewModel.Name} {productFormViewModel.Description}");
            //return View("~/Product/ProductForm", productFormViewModel);

            var setResult = ProductRepository.SetProduct(new ProductFormDto()
            {
                Id = productFormViewModel.Id,
                Name = productFormViewModel.Name,
                AddDate = productFormViewModel.AddDate,
                Description = productFormViewModel.Description,
                ShowProduct = productFormViewModel.ShowProduct,
                SelectedCategory = productFormViewModel.SelectedCategory,
                ProductCondition = productFormViewModel.SelectedProductCondition
            });
            if (setResult)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(productFormViewModel);
        }
    }
}

GeekLab/Views/Shared/Partials/_Footer.cshtml
<footer id="footer" class="background-color-light border-0 mt-0">
    <div class="container">
        <div class="row">
            <div class="col text-center mb-0">
                <ul class="social-icons social-icons-dark">
                    <li class="social-icons-facebook"><a href="http://www.facebook.com/" target="_blank" title="Facebook"><i class="fab fa-facebook-f"></i></a></li>
                    <li class="social-icons-twitter"><a href="http://www.twitter.com/" target="_blank" title="Twitter"><i class="fab fa-twitter"></i></a></li>
                    <li class="social-icons-linkedin"><a href="http://www.linkedin.com/" target="_blank" title="Linkedin"><i class="fab fa-linkedin-in"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright background-color-light border-0 mt-0 mb-5">
        <div class="container">
            <div class="row">
                <div class="col">
                    <p class="text-center text-muted">© Copyright 2018 by Okler. All Rights Reserved.</p>
                </div>
            </div>
        </div>
    </div>
</footer>

GeekLab/Views/Shared/Partials/_Header.cshtml
<header id="header" data-plugin-options="{'stickyEnabled': true, 'stickyEnableOnBoxed': true, 'stickyEnableOnMobile': true, 'stickyStartAt': 55, 'stickySetTop': '-55px', 'stickyChangeLogo': true}" style="min-height: 127.36px;">
    <div class="header-body" style="top: 0px;">
        <div class="header-container container">
            <div class="header-row">
                <div class="header-column">
                    <div class="header-row">
                        <div class="header-logo" style="width: 111px; height: 54px;">
                            <a href="index.html">
                                <img alt="Porto" width="111" height="54" data-sticky-width="82" data-sticky-height="40" data-sticky-top="33" src="img/logo.png" style="top: 0px; width: 111px; height: 54px;">
                            </a>
                        </div>
                    </div>
                </div>
                <div class="header-column justify-content-end">
                    <div class="header-row pt-3">
                        <nav class="header-nav-top">
                            <ul class="nav nav-pills">
                                @if (!User.Identity.IsAuthenticated)
                                {
                                    <li class="nav-item d-none d-sm-block">
                                        <a class="nav-link" asp-controller="Account" asp-action="Login">
                                            <i class="fa fa-angle-right"></i> Login
                                        </a>
                                    </li>
                                }
                                else
                                {
                                    <li class="nav-item d-none d-sm-block">
                                        <a class="nav-link" asp-controller="Account" asp-action="Logout">
                                            <i class="fa fa-angle-right"></i> Logout
                                        </a>
                                    </li>
                                }

                            </ul>
                        </nav>
                    </div>
                    <div class="header-row">
                        <div class="header-nav">
                            <div class="header-nav-main header-nav-main-effect-1 header-nav-main-sub-effect-1">
                                <nav class="collapse">
                                    <ul class="nav nav-pills" id="mainNav">
                                        <li class="dropdown">
                                            <a class="dropdown-item dropdown-toggle active" asp-controller="Home" asp-action="Index">
                                                Home
                                                <i class="fa fa-caret-down"></i>
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a class="dropdown-item" asp-controller="Category" asp-action="Index">
                                                        Categories
                                                    </a>
                                                </li>

                                            </ul>
                                        </li>
                                        <li class="dropdown">
                                            <a class="dropdown-item dropdown-toggle active" asp-controller="Product" asp-action="Index">
                                                Products
                                                <i class="fa fa-caret-down"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                            <ul class="header-social-icons social-icons d-none d-sm-block">
                                <li class="social-icons-facebook"><a href="http://www.facebook.com/" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                                <li class="social-icons-twitter"><a href="http://www.twitter.com/" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                                <li class="social-icons-linkedin"><a href="http://www.linkedin.com/" target="_blank" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                            <button class="btn header-btn-collapse-nav" data-toggle="collapse" data-target=".header-nav-main nav">
                                <i class="fa fa-bars"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

GeekLab/Views/Shared/Partials/_PageHeader.cshtml
@using GeekLab.ViewModels.Base
@model GeekLabViewModel
<section class="page-header">
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>@Model.PageTitle</h1>
            </div>
        </div>
    </div>
</section>

GeekLab/Views/Shared/Partials/_SharedScripts.cshtml
 <!-- Vendor -->
<script src="~/lib/jquery/jquery.min.js"></script>
<script src="~/lib/jquery.appear/jquery.appear.min.js"></script>
<script src="~/lib/jquery.easing/jquery.easing.min.js"></script>
<script src="~/lib/jquery-cookie/jquery-cookie.min.js"></script>
<script src="~/lib/popper/umd/popper.min.js"></script>
<script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
<script src="~/lib/common/common.min.js"></script>
<script src="~/lib/jquery.lazyload/jquery.lazyload.min.js"></script>
<script src="~/lib/isotope/jquery.isotope.min.js"></script>
<script src="~/lib/owl.carousel/owl.carousel.min.js"></script>
<script src="~/lib/magnific-popup/jquery.magnific-popup.min.js"></script>
<script src="~/lib/vide/vide.min.js"></script>

<!-- Theme Base, Components and Settings -->
<script src="~/js/theme/theme.js"></script>

<!-- Theme Custom -->
<script src="~/js/theme/custom.js"></script>

<!-- Theme Initialization Files -->
<script src="~/js/theme/theme.init.js"></script>


<script src="~/lib/iziToastr/js/iziToast.min.js"></script>

GeekLab/Views/Shared/Partials/_SharedStyles.cshtml
<!-- Favicon -->
<link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" />
<link rel="apple-touch-icon" href="img/apple-touch-icon.png">

<!-- Mobile Metas -->
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

<!-- Web Fonts  -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light" rel="stylesheet" type="text/css">

<!-- Vendor CSS -->
<link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome-all.min.css">
<link rel="stylesheet" href="~/lib/animate/animate.min.css">
<link rel="stylesheet" href="~/lib/simple-line-icons/css/simple-line-icons.min.css">
<link rel="stylesheet" href="~/lib/owl.carousel/assets/owl.carousel.min.css">
<link rel="stylesheet" href="~/lib/owl.carousel/assets/owl.theme.default.min.css">
<link rel="stylesheet" href="~/lib/magnific-popup/magnific-popup.min.css">

<!-- Theme CSS -->
<link rel="stylesheet" href="~/css/theme/theme.css">
<link rel="stylesheet" href="~/css/theme/theme-elements.css">
<link rel="stylesheet" href="~/css/theme/theme-blog.css">
<link rel="stylesheet" href="~/css/theme/theme-shop.css">

<!-- Skin CSS -->
<link rel="stylesheet" href="~/css/theme/default.css">

<!-- Theme Custom CSS -->
<link rel="stylesheet" href="~/css/theme/custom.css">
<link href="~/css/site.css" rel="stylesheet" />

<link href="~/lib/iziToastr/css/iziToast.min.css" rel="stylesheet" />