GeekLab/ViewModels/Store/StoreFormViewModel.cs
using GeekLab.Commerce.Dto.Category;
using GeekLab.ViewModels.Base;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GeekLab.ViewModels.Store
{
    public class StoreFormViewModel:GeekLabViewModel
    {
        public StoreFormViewModel()
        {
            PageTitle = "Store form";
        }
        [HiddenInput]
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public string Address { get; set; }
        [HiddenInput]
        public double Longitude { get; set; }
        [HiddenInput]
        public double Latitude { get; set; }
        public IEnumerable<CategoryDto> Categories { get; set; }
    }
}

GeekLab/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GeekLab.Commerce.Dto.Store;
using GeekLab.Commerce.IData.Interfaces;
using GeekLab.Utils;
using GeekLab.ViewModels.Store;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace GeekLab.Controllers
{
    public class StoreController : Controller
    {
        private ICategoryRepository CategoryRepository { get; }
        private IStoreRepository StoreRepository { get; }

        public StoreController(ICategoryRepository categoryRepository
            , IStoreRepository storeRepository)
        {
            CategoryRepository = categoryRepository;
            StoreRepository = storeRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult StoreForm(int?id)
        {
            var vm = new StoreFormViewModel()
            {
                Categories = CategoryRepository.GetCategories()
            };
            return View(vm);
        }

        [HttpPost]
        public IActionResult StoreForm(StoreFormViewModel storeFormViewModel)
        {
            var setResult = StoreRepository.SetStore(new StoreFormDto()
            {
                Id=storeFormViewModel.Id,
                CategoryId=storeFormViewModel.CategoryId,
                Address=storeFormViewModel.Address,
                Latitude= storeFormViewModel.Latitude,
                Longitude=storeFormViewModel.Longitude,
                Name=storeFormViewModel.Name
            });
            if (setResult)
            {
                return RedirectToAction
                    (nameof(HomeController.Index), nameof(HomeController).ToActionName());
            }
            return View(storeFormViewModel);
        }
    }
}

GeekLab/Views/Store/StoreForm.cshtml
@using GeekLab.ViewModels.Store
@model StoreFormViewModel

@section Styles{ 
<link href="~/lib/mapbox/css/mapbox-gl.css" rel="stylesheet" />
}
<div class="container">
    <h2>Store Form</h2>
    <form method="post"
          asp-controller="Store"
          asp-action="StoreForm">
        <div class="row">
            <div class="col-md-12 form-group">
                <label asp-for="Name">Name</label>
                <input asp-for="Name"
                       class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 form-group">
                <label asp-for="CategoryId">Category</label>
                <select asp-for="CategoryId"
                        class="form-control">
                    @foreach (var categoryDto in Model.Categories)
                    {
                        <option value="@categoryDto.Id">@categoryDto.Name</option>
                    }
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 form-group">
                <label asp-for="Address">Address</label>
                <textarea asp-for="Address"
                          class="form-control">
                </textarea>
            </div>
        </div>


        <div class="row">
            <div class="col-md-12">
                <div id="map"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <button type="submit"
                        class="btn btn-info float-right">
                    Save
                </button>
            </div>
        </div>
        <input asp-for="Id" />
        <input asp-for="Latitude" />
        <input asp-for="Longitude" />
    </form>
</div>

@section Scripts{ 
    <script src="~/lib/mapbox/js/mapbox-gl.js"></script>
    <script src="~/js/views/store/storeForm.js"></script>
}